class Country {
  final String name;
  final String flag;

  Country({required this.name, required this.flag});

  factory Country.fromJson(Map<String, dynamic> json) {
    return Country(
      name: json['translations']['ar'],
      flag: json['flag'],
    );
  }
}

List<String> quranAhzabAya = [
  "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
  "افتطمعون تن ي,منوا لكم",
  "سيقول السفهاء من الناس",
  "واذكروا الله في أيام",
  "تلك الرسل فضلنا",
  "قل أونبئكم بخير من",
  "كل الطعام كان حلا",
  "يستبشرون بنعمة من",
  "والمحصنات من النساء",
  "فما لكم في المنافقين",
  "لا يحب الله الجهر",
  "وانل عليهم نبأ بني",
  "لتجدن أشد الناس",
  "انما يستجيب الذين",
  "ولو نزلنا أليهم",
  "ألمص",
  "قال الملأ الذين",
  "وأذ نتقنا الجبل فوقهم",
  "واعلموا أنما غنمتم من",
  "يا أيها الذين امنوا ان",
  "انما السبيل على الذين",
  "للذين احسنوا الحسنى",
  "وما من دابة في الأرض",
  "والى مدين اخوهم شعيبا",
  "وما أبرئ نفسي",
  "أفمن يعلم أنما أنزل",
  "الر تلك أيات الكتاب",
  "وقال الله لا تتخذوا",
  "سبحان الذين أسرى بعبده",
  "أولم يروا أن الله الذي",
  "قال ام أقل لك انك",
  "طه",
  "اقترب للناس حسابهم",
  "يا أيها الناس اتقوا",
  "قد المؤمنون",
  "يا أيها الذين امنوا لا",
  "و قال الذين لا يرجون",
  "قالوا أنومن لك و اتبعك",
  "قما كان جةاب قومه الا",
  "ولقد وصلنا لهم القول",
  "ولا تجادلوا أهل الكتاب",
  "ومن يسلم وجهه الى الله",
  "ومن يقنت منكن لله",
  "قل من يرزقكم",
  "وما أنزلنا على قومه من",
  "فنبذناه بالعراء وهو",
  "فمن اظلم ممن كذب على",
  "ويا قوم ما لي أدعوكم الى",
  "اليه يرد علمم الساعة",
  "قال أولو جئتكم بأهدى",
  "حم",
  "لقد رضي الله",
  "قال فما خطبكم أيها",
  "الرحمن",
  "قد السمع قول التي",
  "يسبح لله ما في",
  "تبارك الذي بيده الملك",
  "قل أوحيب الي أنه",
  "عم",
  "سبح اسم ربك الأعلى",
];

List quranAhzabStartPage = [
  1,
  11,
  22,
  32,
  42,
  51,
  62,
  72,
  82,
  92,
  102,
  112,
  121,
  132,
  142,
  151,
  162,
  173,
  182,
  192,
  201,
  212,
  222,
  231,
  242,
  252,
  262,
  272,
  282,
  292,
  302,
  312,
  322,
  332,
  342,
  352,
  362,
  371,
  382,
  392,
  402,
  413,
  422,
  431,
  442,
  451,
  462,
  472,
  482,
  491,
  502,
  513,
  522,
  531,
  542,
  553,
  562,
  572,
  582,
  591
];
List quranAhzabStartPage2 = [
  1,
  11,
  22,
  32,
  42,
  51,
  62,
  72,
  82,
  92,
  102,
  112,
  121,
  132,
  142,
  151,
  162,
  173,
  182,
  192,
  201,
  212,
  222,
  231,
  242,
  252,
  262,
  272,
  282,
  292,
  302,
  312,
  322,
  332,
  342,
  352,
  362,
  371,
  382,
  392,
  402,
  413,
  422,
  431,
  442,
  451,
  462,
  472,
  482,
  491,
  502,
  513,
  522,
  531,
  542,
  553,
  562,
  572,
  582,
  591
];

List quranAhzabEndPage = [
  11,
  21,
  31,
  41,
  51,
  62,
  72,
  81,
  92,
  101,
  112,
  121,
  131,
  141,
  150,
  161,
  172,
  181,
  192,
  201,
  211,
  221,
  231,
  241,
  251,
  261,
  272,
  281,
  292,
  301,
  312,
  321,
  331,
  341,
  351,
  361,
  371,
  381,
  391,
  401,
  413,
  421,
  431,
  441,
  451,
  461,
  471,
  481,
  491,
  502,
  513,
  521,
  531,
  541,
  552,
  561,
  571,
  581,
  591,
  604
];

List<String> quranAhzabStartAya = [
  "الفاتحة",
  "البفرة",
  "البقرة",
  "البقرة",
  "البقرة",
  "أل عمران",
  "أل عمران",
  "أل عمران",
  "النساء",
  "النساء",
  "النساء",
  "المائدة",
  "المائدة",
  "الأتعام",
  "الأنعام",
  "الأعراف",
  "الأعراف",
  "الأعراف",
  "الأنفال",
  "التوبة",
  "التوبة",
  "يونس",
  "هود",
  "هود",
  "يوسف",
  "الرعد",
  "الحجر",
  "النحل",
  "الاسراء",
  "الاسراء",
  "الكهف",
  "طه",
  "الأنبياء",
  "الحج",
  "المؤمنون",
  "النور",
  "الفرقان",
  "الشعراء",
  "النمل",
  "القصص",
  "العنكبوت",
  "لقمان",
  "الأحزاب",
  "سبأ",
  "يس",
  "الصافات",
  "الزمر",
  "غافر",
  "فصلت",
  "الزخرف",
  "الأحقاق",
  "الفتح",
  "الذاريات",
  "الرحمن",
  "المجادلة",
  "الجمعة",
  "الملك",
  "الجن",
  "النبأ",
  "الأعلى",
];

List<String> quranAhzabEndAya = [
  "البقرة",
  "البقرة",
  "البقرة",
  "البقرة",
  "أل عمران",
  "أل عمران",
  "أل عمران",
  "النساء",
  "النساء",
  "النساء",
  "المائدة",
  "المائدة",
  "الأنعام",
  "الأنعام",
  "الأنعام",
  "الأعراف",
  "الأعراف",
  "الأنفال",
  "التوبة",
  "التوبة",
  "يونس",
  "هود",
  "هود",
  "يوسف",
  "الرعد",
  "ابراهيم",
  "النحل",
  "النحل",
  "الأسراء",
  "الكهف",
  "مريم",
  "طه",
  "الأنبياء",
  "الحج",
  "النور",
  "الفرقان",
  "الشعراء",
  "النمل",
  "القصص",
  "العنكبوت",
  "لقمان",
  "الأحزاب",
  "سبأ",
  "يس",
  "الصافات",
  "الزمر",
  "غافر",
  "فصلت",
  "الوخرف",
  "الجاثية",
  "الفتح",
  "الذاريات",
  "القمر",
  "الحديد",
  "الصف",
  "التحريم",
  "نوح",
  "المرسلات",
  "الطارق",
  "الناس",
];

List quranSurahStartIndex = [
  1,
  75,
  142,
  203,
  253,
  15,
  93,
  171,
  24,
  88,
  148,
  27,
  82,
  36,
  111,
  1,
  88,
  171,
  41,
  43,
  93,
  26,
  6,
  84,
  53,
  19,
  1,
  51,
  1,
  99,
  42,
  1,
  1,
  1,
  1,
  21,
  21,
  111,
  56,
  51,
  46,
  22,
  31,
  24,
  28,
  145,
  32,
  41,
  47,
  24,
  1,
  18,
  31,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
];
List quranSurahEndIndex = [
  74,
  141,
  202,
  252,
  14,
  92,
  170,
  23,
  87,
  147,
  26,
  81,
  35,
  110,
  165,
  87,
  170,
  40,
  33,
  92,
  25,
  5,
  83,
  52,
  18,
  52,
  50,
  128,
  98,
  74,
  98,
  135,
  112,
  78,
  20,
  20,
  110,
  55,
  50,
  12,
  21,
  30,
  23,
  27,
  144,
  31,
  40,
  13,
  023,
  37,
  17,
  30,
  55,
  29,
  14,
  12,
  28,
  50,
  17,
  6,
];
List<String> quranSurahs = [
  "الفاتحة",
  "البقرة",
  "آل عمران",
  "النساء",
  "المائدة",
  "الأنعام",
  "الأعراف",
  "الأنفال",
  "التوبة",
  "يونس",
  "هود",
  "يوسف",
  "الرعد",
  "إبراهيم",
  "الحجر",
  "النحل",
  "الإسراء",
  "الكهف",
  "مريم",
  "طه",
  "الأنبياء",
  "الحج",
  "المؤمنون",
  "النور",
  "الفرقان",
  "الشعراء",
  "النمل",
  "القصص",
  "العنكبوت",
  "الروم",
  "لقمان",
  "السجدة",
  "الأحزاب",
  "سبأ",
  "فاطر",
  "يس",
  "الصافات",
  "ص",
  "الزمر",
  "غافر",
  "فصلت",
  "الشورى",
  "الزخرف",
  "الدخان",
  "الجاثية",
  "الأحقاف",
  "محمد",
  "الفتح",
  "الحجرات",
  "ق",
  "الذاريات",
  "الطور",
  "النجم",
  "القمر",
  "الرحمن",
  "الواقعة",
  "الحديد",
  "المجادلة",
  "الحشر",
  "الممتحنة",
  "الصف",
  "الجمعة",
  "المنافقون",
  "التغابن",
  "الطلاق",
  "التحريم",
  "الملك",
  "القلم",
  "الحاقة",
  "المعارج",
  "نوح",
  "الجن",
  "المزمل",
  "المدثر",
  "القيامة",
  "الإنسان",
  "المرسلات",
  "النبأ",
  "النازعات",
  "عبس",
  "التكوير",
  "الإنفطار",
  "المطففين",
  "الإنشقاق",
  "البروج",
  "الطارق",
  "الأعلى",
  "الغاشية",
  "الفجر",
  "البلد",
  "الشمس",
  "الليل",
  "الضحى",
  "الشرح",
  "التين",
  "العلق",
  "القدر",
  "البينة",
  "الزلزلة",
  "العاديات",
  "القارعة",
  "التكاثر",
  "العصر",
  "الهمزة",
  "الفيل",
  "قريش",
  "الماعون",
  "الكوثر",
  "الكافرون",
  "النصر",
  "المسد",
  "الإخلاص",
  "الفلق",
  "الناس"
];
List<String> numbers = [
  'الاول',
  'الثاني',
  'الثالث',
  'الرابع',
  'الخامس',
  'السادس',
  'السابع',
  'الثامن',
  'التاسع',
  'العاشر',
  'الحادي عشر',
  'الثاني عشر',
  'الثالث عشر',
  'الرابع عشر',
  'الخامس عشر',
  'السادس عشر',
  'السابع عشر',
  'الثامن عشر',
  'التاسع عشر',
  'العشرون',
  'الحادي والعشرون',
  'الثاني والعشرون',
  'الثالث والعشرون',
  'الرابع والعشرون',
  'الخامس والعشرون',
  'السادس والعشرون',
  'السابع والعشرون',
  'الثامن والعشرون',
  'التاسع والعشرون',
  'الثلاثون',
];
List surah_juzz = [
  1,
  22,
  42,
  62,
  82,
  102,
  121,
  142,
  162,
  182,
  201,
  222,
  242,
  262,
  282,
  302,
  322,
  342,
  362,
  382,
  402,
  422,
  442,
  462,
  482,
  502,
  522,
  542,
  562,
  582
];

List quranSurahsPage = [
  1,
  2,
  50,
  77,
  106,
  128,
  151,
  177,
  187,
  208,
  221,
  235,
  249,
  255,
  262,
  267,
  282,
  293,
  305,
  312,
  322,
  332,
  342,
  350,
  359,
  367,
  377,
  385,
  396,
  104,
  411,
  415,
  418,
  428,
  434,
  440,
  446,
  453,
  458,
  467,
  477,
  483,
  489,
  496,
  499,
  502,
  507,
  511,
  515,
  518,
  520,
  523,
  526,
  528,
  531,
  534,
  537,
  542,
  545,
  549,
  551,
  553,
  554,
  556,
  558,
  560,
  562,
  564,
  566,
  568,
  570,
  572,
  574,
  575,
  577,
  578,
  580,
  582,
  583,
  585,
  586,
  587,
  587,
  589,
  590,
  591,
  591,
  592,
  593,
  594,
  595,
  595,
  596,
  596,
  597,
  597,
  598,
  598,
  599,
  599,
  600,
  600,
  601,
  601,
  601,
  602,
  602,
  602,
  603,
  603,
  603,
  604,
  604,
  604,
];

List switchSurahName(int page) {
  List surahUrl;
  switch (page) {
    case 1:
      surahUrl = ['assets/PDF/output_folder/page_1.png'];
      break;
    case (>= 2 || < 50):
      surahUrl = [
        'assets/PDF/output_folder/page_1.png',
        'assets/PDF/output_folder/page_2.png',
        'assets/PDF/output_folder/page_3.png',
        'assets/PDF/output_folder/page_4.png',
        'assets/PDF/output_folder/page_5.png',
        'assets/PDF/output_folder/page_6.png',
        'assets/PDF/output_folder/page_7.png',
        'assets/PDF/output_folder/page_8.png',
        'assets/PDF/output_folder/page_9.png',
        'assets/PDF/output_folder/page_10.png',
        'assets/PDF/output_folder/page_11.png',
        'assets/PDF/output_folder/page_12.png',
        'assets/PDF/output_folder/page_13.png',
        'assets/PDF/output_folder/page_14.png',
        'assets/PDF/output_folder/page_15.png',
        'assets/PDF/output_folder/page_16.png',
        'assets/PDF/output_folder/page_17.png',
        'assets/PDF/output_folder/page_18.png',
        'assets/PDF/output_folder/page_19.png',
        'assets/PDF/output_folder/page_20.png',
        'assets/PDF/output_folder/page_21.png',
        'assets/PDF/output_folder/page_22.png',
        'assets/PDF/output_folder/page_23.png',
        'assets/PDF/output_folder/page_24.png',
        'assets/PDF/output_folder/page_25.png',
        'assets/PDF/output_folder/page_26.png',
        'assets/PDF/output_folder/page_27.png',
        'assets/PDF/output_folder/page_28.png',
        'assets/PDF/output_folder/page_29.png',
        'assets/PDF/output_folder/page_30.png',
        'assets/PDF/output_folder/page_31.png',
        'assets/PDF/output_folder/page_32.png',
        'assets/PDF/output_folder/page_33.png',
        'assets/PDF/output_folder/page_34.png',
        'assets/PDF/output_folder/page_35.png',
        'assets/PDF/output_folder/page_36.png',
        'assets/PDF/output_folder/page_37.png',
        'assets/PDF/output_folder/page_38.png',
        'assets/PDF/output_folder/page_39.png',
        'assets/PDF/output_folder/page_40.png',
        'assets/PDF/output_folder/page_41.png',
        'assets/PDF/output_folder/page_42.png',
        'assets/PDF/output_folder/page_43.png',
        'assets/PDF/output_folder/page_44.png',
        'assets/PDF/output_folder/page_45.png',
        'assets/PDF/output_folder/page_46.png',
        'assets/PDF/output_folder/page_47.png',
        'assets/PDF/output_folder/page_48.png',
        'assets/PDF/output_folder/page_49.png',
      ];
      break;
    case (>= 50 || < 77):
      surahUrl = [
        'assets/PDF/output_folder/page_50.png',
        'assets/PDF/output_folder/page_51.png',
        'assets/PDF/output_folder/page_52.png',
        'assets/PDF/output_folder/page_53.png',
        'assets/PDF/output_folder/page_54.png',
        'assets/PDF/output_folder/page_55.png',
        'assets/PDF/output_folder/page_56.png',
        'assets/PDF/output_folder/page_57.png',
        'assets/PDF/output_folder/page_58.png',
        'assets/PDF/output_folder/page_59.png',
        'assets/PDF/output_folder/page_60.png',
        'assets/PDF/output_folder/page_61.png',
        'assets/PDF/output_folder/page_62.png',
        'assets/PDF/output_folder/page_63.png',
        'assets/PDF/output_folder/page_64.png',
        'assets/PDF/output_folder/page_65.png',
        'assets/PDF/output_folder/page_66.png',
        'assets/PDF/output_folder/page_67.png',
        'assets/PDF/output_folder/page_68.png',
        'assets/PDF/output_folder/page_69.png',
        'assets/PDF/output_folder/page_70.png',
        'assets/PDF/output_folder/page_71.png',
        'assets/PDF/output_folder/page_72.png',
        'assets/PDF/output_folder/page_73.png',
        'assets/PDF/output_folder/page_74.png',
        'assets/PDF/output_folder/page_75.png',
        'assets/PDF/output_folder/page_76.png',
        'assets/PDF/output_folder/page_77.png',
      ];
      break;
    case (>= 77 || < 106):
      surahUrl = [
        'assets/PDF/output_folder/page_77.png',
        'assets/PDF/output_folder/page_78.png',
        'assets/PDF/output_folder/page_79.png',
        'assets/PDF/output_folder/page_80.png',
        'assets/PDF/output_folder/page_81.png',
        'assets/PDF/output_folder/page_82.png',
        'assets/PDF/output_folder/page_83.png',
        'assets/PDF/output_folder/page_84.png',
        'assets/PDF/output_folder/page_85.png',
        'assets/PDF/output_folder/page_86.png',
        'assets/PDF/output_folder/page_87.png',
        'assets/PDF/output_folder/page_88.png',
        'assets/PDF/output_folder/page_89.png',
        'assets/PDF/output_folder/page_90.png',
        'assets/PDF/output_folder/page_91.png',
        'assets/PDF/output_folder/page_92.png',
        'assets/PDF/output_folder/page_93.png',
        'assets/PDF/output_folder/page_94.png',
        'assets/PDF/output_folder/page_95.png',
        'assets/PDF/output_folder/page_96.png',
        'assets/PDF/output_folder/page_97.png',
        'assets/PDF/output_folder/page_98.png',
        'assets/PDF/output_folder/page_99.png',
        'assets/PDF/output_folder/page_100.png',
        'assets/PDF/output_folder/page_101.png',
        'assets/PDF/output_folder/page_102.png',
        'assets/PDF/output_folder/page_103.png',
        'assets/PDF/output_folder/page_104.png',
        'assets/PDF/output_folder/page_105.png',
      ];

      break;
    case (>= 106 || < 128):
      surahUrl = [
        'assets/PDF/output_folder/page_106.png',
        'assets/PDF/output_folder/page_107.png',
        'assets/PDF/output_folder/page_108.png',
        'assets/PDF/output_folder/page_109.png',
        'assets/PDF/output_folder/page_110.png',
        'assets/PDF/output_folder/page_111.png',
        'assets/PDF/output_folder/page_112.png',
        'assets/PDF/output_folder/page_113.png',
        'assets/PDF/output_folder/page_114.png',
        'assets/PDF/output_folder/page_115.png',
        'assets/PDF/output_folder/page_116.png',
        'assets/PDF/output_folder/page_117.png',
        'assets/PDF/output_folder/page_118.png',
        'assets/PDF/output_folder/page_119.png',
        'assets/PDF/output_folder/page_120.png',
        'assets/PDF/output_folder/page_121.png',
        'assets/PDF/output_folder/page_122.png',
        'assets/PDF/output_folder/page_123.png',
        'assets/PDF/output_folder/page_124.png',
        'assets/PDF/output_folder/page_125.png',
        'assets/PDF/output_folder/page_126.png',
        'assets/PDF/output_folder/page_127.png',
      ];
      break;
    case (>= 128 || < 151):
      surahUrl = [
        'assets/PDF/output_folder/page_128.png',
        'assets/PDF/output_folder/page_129.png',
        'assets/PDF/output_folder/page_130.png',
        'assets/PDF/output_folder/page_131.png',
        'assets/PDF/output_folder/page_132.png',
        'assets/PDF/output_folder/page_133.png',
        'assets/PDF/output_folder/page_134.png',
        'assets/PDF/output_folder/page_135.png',
        'assets/PDF/output_folder/page_136.png',
        'assets/PDF/output_folder/page_137.png',
        'assets/PDF/output_folder/page_138.png',
        'assets/PDF/output_folder/page_139.png',
        'assets/PDF/output_folder/page_140.png',
        'assets/PDF/output_folder/page_141.png',
        'assets/PDF/output_folder/page_142.png',
        'assets/PDF/output_folder/page_143.png',
        'assets/PDF/output_folder/page_144.png',
        'assets/PDF/output_folder/page_145.png',
        'assets/PDF/output_folder/page_146.png',
        'assets/PDF/output_folder/page_147.png',
        'assets/PDF/output_folder/page_148.png',
        'assets/PDF/output_folder/page_149.png',
        'assets/PDF/output_folder/page_150.png',
      ];
      break;
    case (>= 151 || < 177):
      surahUrl = [
        'assets/PDF/output_folder/page_151.png',
        'assets/PDF/output_folder/page_152.png',
        'assets/PDF/output_folder/page_153.png',
        'assets/PDF/output_folder/page_154.png',
        'assets/PDF/output_folder/page_155.png',
        'assets/PDF/output_folder/page_156.png',
        'assets/PDF/output_folder/page_157.png',
        'assets/PDF/output_folder/page_158.png',
        'assets/PDF/output_folder/page_159.png',
        'assets/PDF/output_folder/page_160.png',
        'assets/PDF/output_folder/page_161.png',
        'assets/PDF/output_folder/page_162.png',
        'assets/PDF/output_folder/page_163.png',
        'assets/PDF/output_folder/page_164.png',
        'assets/PDF/output_folder/page_165.png',
        'assets/PDF/output_folder/page_166.png',
        'assets/PDF/output_folder/page_167.png',
        'assets/PDF/output_folder/page_168.png',
        'assets/PDF/output_folder/page_169.png',
        'assets/PDF/output_folder/page_170.png',
        'assets/PDF/output_folder/page_171.png',
        'assets/PDF/output_folder/page_172.png',
        'assets/PDF/output_folder/page_173.png',
        'assets/PDF/output_folder/page_174.png',
        'assets/PDF/output_folder/page_175.png',
        'assets/PDF/output_folder/page_176.png',
      ];
      break;
    case (>= 177 || < 187):
      surahUrl = [
        'assets/PDF/output_folder/page_177.png',
        'assets/PDF/output_folder/page_178.png',
        'assets/PDF/output_folder/page_179.png',
        'assets/PDF/output_folder/page_180.png',
        'assets/PDF/output_folder/page_181.png',
        'assets/PDF/output_folder/page_182.png',
        'assets/PDF/output_folder/page_183.png',
        'assets/PDF/output_folder/page_184.png',
        'assets/PDF/output_folder/page_185.png',
        'assets/PDF/output_folder/page_186.png',
      ];
      break;
    case (>= 187 || < 208):
      surahUrl = [
        'assets/PDF/output_folder/page_187.png',
        'assets/PDF/output_folder/page_188.png',
        'assets/PDF/output_folder/page_189.png',
        'assets/PDF/output_folder/page_190.png',
        'assets/PDF/output_folder/page_191.png',
        'assets/PDF/output_folder/page_192.png',
        'assets/PDF/output_folder/page_193.png',
        'assets/PDF/output_folder/page_194.png',
        'assets/PDF/output_folder/page_195.png',
        'assets/PDF/output_folder/page_196.png',
        'assets/PDF/output_folder/page_197.png',
        'assets/PDF/output_folder/page_198.png',
        'assets/PDF/output_folder/page_199.png',
        'assets/PDF/output_folder/page_200.png',
        'assets/PDF/output_folder/page_201.png',
        'assets/PDF/output_folder/page_202.png',
        'assets/PDF/output_folder/page_203.png',
        'assets/PDF/output_folder/page_204.png',
        'assets/PDF/output_folder/page_205.png',
        'assets/PDF/output_folder/page_206.png',
        'assets/PDF/output_folder/page_207.png',
      ];
      break;
    case (>= 208 || < 221):
      surahUrl = [
        'assets/PDF/output_folder/page_208.png',
        'assets/PDF/output_folder/page_209.png',
        'assets/PDF/output_folder/page_210.png',
        'assets/PDF/output_folder/page_211.png',
        'assets/PDF/output_folder/page_212.png',
        'assets/PDF/output_folder/page_213.png',
        'assets/PDF/output_folder/page_214.png',
        'assets/PDF/output_folder/page_215.png',
        'assets/PDF/output_folder/page_216.png',
        'assets/PDF/output_folder/page_217.png',
        'assets/PDF/output_folder/page_218.png',
        'assets/PDF/output_folder/page_219.png',
        'assets/PDF/output_folder/page_220.png',
      ];
      break;
    // Add more cases for other page numbers as needed
    case (>= 221 || < 235):
      surahUrl = [
        'assets/PDF/output_folder/page_221.png',
        'assets/PDF/output_folder/page_222.png',
        'assets/PDF/output_folder/page_223.png',
        'assets/PDF/output_folder/page_224.png',
        'assets/PDF/output_folder/page_225.png',
        'assets/PDF/output_folder/page_226.png',
        'assets/PDF/output_folder/page_227.png',
        'assets/PDF/output_folder/page_228.png',
        'assets/PDF/output_folder/page_229.png',
        'assets/PDF/output_folder/page_230.png',
        'assets/PDF/output_folder/page_231.png',
        'assets/PDF/output_folder/page_232.png',
        'assets/PDF/output_folder/page_233.png',
        'assets/PDF/output_folder/page_234.png',
      ];
      break;
    case (>= 235 || < 249):
      surahUrl = [
        'assets/PDF/output_folder/page_235.png',
        'assets/PDF/output_folder/page_236.png',
        'assets/PDF/output_folder/page_237.png',
        'assets/PDF/output_folder/page_238.png',
        'assets/PDF/output_folder/page_239.png',
        'assets/PDF/output_folder/page_240.png',
        'assets/PDF/output_folder/page_241.png',
        'assets/PDF/output_folder/page_242.png',
        'assets/PDF/output_folder/page_243.png',
        'assets/PDF/output_folder/page_244.png',
        'assets/PDF/output_folder/page_245.png',
        'assets/PDF/output_folder/page_246.png',
        'assets/PDF/output_folder/page_247.png',
        'assets/PDF/output_folder/page_248.png',
      ];
      break;
    case (>= 249 || < 255):
      surahUrl = [
        'assets/PDF/output_folder/page_249.png',
        'assets/PDF/output_folder/page_250.png',
        'assets/PDF/output_folder/page_251.png',
        'assets/PDF/output_folder/page_252.png',
        'assets/PDF/output_folder/page_253.png',
        'assets/PDF/output_folder/page_254.png',
      ];
      break;
    case (>= 255 || < 262):
      surahUrl = [
        'assets/PDF/output_folder/page_255.png',
        'assets/PDF/output_folder/page_256.png',
        'assets/PDF/output_folder/page_257.png',
        'assets/PDF/output_folder/page_258.png',
        'assets/PDF/output_folder/page_259.png',
        'assets/PDF/output_folder/page_260.png',
        'assets/PDF/output_folder/page_261.png',
      ];
      break;
    case (>= 262 || < 267):
      surahUrl = [
        'assets/PDF/output_folder/page_262.png',
        'assets/PDF/output_folder/page_263.png',
        'assets/PDF/output_folder/page_264.png',
        'assets/PDF/output_folder/page_265.png',
        'assets/PDF/output_folder/page_266.png',
      ];
    //   break;
    // case (>= 267 || < 282):
    //   surahUrl = 'النحل';
    //   break;
    // case (>= 282 || < 293):
    //   surahUrl = 'الإسراء';
    //   break;
    // case (>= 293 || < 305):
    //   surahUrl = 'الكهف';
    //   break;
    // case (>= 305 || < 312):
    //   surahUrl = 'مريم';
    //   break;
    // case (>= 312 || < 322):
    //   surahUrl = 'طه';
    //   break;
    // case (>= 322 || < 332):
    //   surahUrl = 'الأنبياء';
    //   break;
    // case (>= 332 || < 342):
    //   surahUrl = 'الحج';
    //   break;
    // case (>= 342 || < 350):
    //   surahUrl = 'المؤمنون';
    // case (>= 350 || < 359):
    //   surahUrl = 'النور';
    //   break;
    // case (>= 359 || < 367):
    //   surahUrl = 'الفرقان';
    //   break;
    // case (>= 367 || < 377):
    //   surahUrl = 'الشعراء';
    //   break;
    // case (>= 377 && < 385):
    //   surahUrl = 'النمل';
    //   break;
    // case (>= 385 && < 396):
    //   surahUrl = 'القصص';
    //   break;
    // case (>= 396 && < 404):
    //   surahUrl = 'العنكبوت';
    //   break;
    // case (>= 404 && < 411):
    //   surahUrl = 'الروم';
    //   break;
    // case (>= 411 && < 415):
    //   surahUrl = 'لقمان';
    //   break;
    // case (>= 415 && < 418):
    //   surahUrl = 'السجدة';
    //   break;
    // case (>= 418 && < 428):
    //   surahUrl = 'الأحزاب';
    //   break;
    // case (>= 428 && < 434):
    //   surahUrl = 'سبأ';
    //   break;
    // case (>= 434 && < 440):
    //   surahUrl = 'فاطر';
    //   break;
    // case (>= 440 && < 446):
    //   surahUrl = 'يس';
    //   break;
    // case (>= 446 && < 453):
    //   surahUrl = 'الصافات';
    //   break;
    // case (>= 453 && < 458):
    //   surahUrl = 'ص';
    //   break;
    // case (>= 458 && < 467):
    //   surahUrl = 'الزمر';
    //   break;
    // case (>= 467 && < 477):
    //   surahUrl = 'غافر';
    //   break;
    // case (>= 477 && < 483):
    //   surahUrl = 'فصلت';
    //   break;
    // case (>= 483 && < 489):
    //   surahUrl = 'الشورى';
    //   break;
    // case (>= 489 && < 496):
    //   surahUrl = 'الزخرف';
    //   break;
    // case (>= 496 && < 499):
    //   surahUrl = 'الدخان';
    //   break;
    // case (>= 499 && < 502):
    //   surahUrl = 'الجاثية';
    //   break;
    // case (>= 502 && < 507):
    //   surahUrl = 'الأحقاف';
    //   break;
    // case (>= 507 && < 511):
    //   surahUrl = 'محمد';
    //   break;
    // case (>= 511 && < 515):
    //   surahUrl = 'الفتح';
    //   break;
    // case (>= 515 && < 518):
    //   surahUrl = 'الحشر';
    //   break;
    // case (>= 518 && < 520):
    //   surahUrl = 'ق';
    //   break;
    // case (>= 520 && < 523):
    //   surahUrl = 'الذاريات';
    //   break;
    // case (>= 523 && < 526):
    //   surahUrl = 'الطور';
    //   break;
    // case (>= 526 && < 528):
    //   surahUrl = 'النجم';
    //   break;
    // case (>= 528 && < 531):
    //   surahUrl = 'القمر';
    //   break;
    // case (>= 531 && < 534):
    //   surahUrl = 'الرحمن';
    //   break;
    // case (>= 534 && < 537):
    //   surahUrl = 'الواقعة';
    //   break;
    // case (>= 537 && < 542):
    //   surahUrl = 'الحديد';
    //   break;
    // case (>= 542 && < 545):
    //   surahUrl = 'المجادلة';
    //   break;
    // case (>= 545 && < 549):
    //   surahUrl = 'الحشر';
    //   break;
    // case (>= 549 && < 551):
    //   surahUrl = 'الممتحنة';
    //   break;
    // case (>= 551 && < 553):
    //   surahUrl = 'الصف';
    //   break;
    // case (>= 553 && < 554):
    //   surahUrl = 'الجمعة';
    //   break;
    // case (>= 554 && < 556):
    //   surahUrl = 'المنافقون';
    //   break;
    // case (>= 556 && < 558):
    //   surahUrl = 'التغابن';
    //   break;
    // case (>= 558 && < 560):
    //   surahUrl = 'الطلاق';
    //   break;
    // case (>= 560 && < 562):
    //   surahUrl = 'التحريم';
    //   break;
    // case (>= 562 && < 564):
    //   surahUrl = 'الملك';
    //   break;
    // case (>= 564 && < 566):
    //   surahUrl = 'القلم';
    //   break;
    // case (>= 566 && < 568):
    //   surahUrl = 'الحاقة';
    //   break;
    // case (>= 568 && < 570):
    //   surahUrl = 'المعارج';
    //   break;
    // case (>= 570 && < 572):
    //   surahUrl = 'نوح';
    //   break;
    // case (>= 572 && < 574):
    //   surahUrl = 'الجن';
    //   break;
    // case (>= 0574 && < 575):
    //   surahUrl = 'المزمل';
    //   break;
    // case (>= 575 && < 577):
    //   surahUrl = 'المدثر';
    //   break;
    // case (>= 577 && < 578):
    //   surahUrl = 'القيامة';
    //   break;
    // case (>= 578 && < 580):
    //   surahUrl = 'الإنسان';
    //   break;
    // case (>= 580 && < 582):
    //   surahUrl = 'المرسلات';
    //   break;
    // case (>= 582 && < 583):
    //   surahUrl = 'النبأ';
    //   break;
    // case (>= 583 && < 585):
    //   surahUrl = 'النازعات';
    //   break;
    // case (>= 585 && < 586):
    //   surahUrl = 'عبس';
    //   break;
    // case (>= 586 && < 586):
    //   surahUrl = 'التكوير';
    //   break;
    // case (586):
    //   surahUrl = 'الإنفطار';
    //   break;
    // case (>= 587 && < 589):
    //   surahUrl = 'المطففين';
    //   break;
    // case (>= 589 && < 590):
    //   surahUrl = 'الإنشقاق';
    //   break;
    // case (>= 590 && < 591):
    //   surahUrl = 'البروج';
    //   break;
    // case 591:
    //   surahUrl = 'الأعلى/الطارق';
    //   break;
    // case 592:
    //   surahUrl = 'الغاشية';
    //   break;
    // case 593:
    //   surahUrl = 'الفجر';
    //   break;
    // case 594:
    //   surahUrl = 'البلد';
    //   break;
    // case 595:
    //   surahUrl = 'الشمس/الليل';
    //   break;
    // case 596:
    //   surahUrl = 'الضحى/الشرح';
    //   break;
    // case 597:
    //   surahUrl = 'التين/العلق';
    //   break;
    // case 598:
    //   surahUrl = 'القدر/البينة';
    //   break;
    // case 599:
    //   surahUrl = 'الزلزلة/العاديات';
    //   break;
    // case 600:
    //   surahUrl = 'القارعة/التكاثر';
    //   break;
    // case 601:
    //   surahUrl = 'العصر/الهمزة/الفيل';

    // case 602:
    //   surahUrl = 'قريش/الماعون/قريش';
    //   break;
    // case 603:
    //   surahUrl = 'الكافرون/النصر/المسد';
    //   break;
    // case 604:
    //   surahUrl = 'الإخلاص/الفلق/الناس';
    //   break;
    default:
      surahUrl = [];
  }
  return surahUrl;
}

List wird = [
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  8,
  8,
  8,
  8,
  8,
  8,
  8,
  8,
  8,
  8,
  8,
  8,
  8,
  8,
  8,
  8,
  8,
  8,
  8,
  8,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  12,
  12,
  12,
  12,
  12,
  12,
  12,
  12,
  12,
  12,
  12,
  12,
  12,
  12,
  12,
  12,
  12,
  12,
  12,
  12,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  17,
  17,
  17,
  17,
  17,
  17,
  17,
  17,
  17,
  17,
  17,
  17,
  17,
  17,
  17,
  17,
  17,
  17,
  17,
  17,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  19,
  19,
  19,
  19,
  19,
  19,
  19,
  19,
  19,
  19,
  19,
  19,
  19,
  19,
  19,
  19,
  19,
  19,
  19,
  19,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  22,
  22,
  22,
  22,
  22,
  22,
  22,
  22,
  22,
  22,
  22,
  22,
  22,
  22,
  22,
  22,
  22,
  22,
  22,
  22,
  23,
  23,
  23,
  23,
  23,
  23,
  23,
  23,
  23,
  23,
  23,
  23,
  23,
  23,
  23,
  23,
  23,
  23,
  23,
  23,
  24,
  24,
  24,
  24,
  24,
  24,
  24,
  24,
  24,
  24,
  24,
  24,
  24,
  24,
  24,
  24,
  24,
  24,
  24,
  24,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  26,
  26,
  26,
  26,
  26,
  26,
  26,
  26,
  26,
  26,
  26,
  26,
  26,
  26,
  26,
  26,
  26,
  26,
  26,
  26,
  27,
  27,
  27,
  27,
  27,
  27,
  27,
  27,
  27,
  27,
  27,
  27,
  27,
  27,
  27,
  27,
  27,
  27,
  27,
  27,
  28,
  28,
  28,
  28,
  28,
  28,
  28,
  28,
  28,
  28,
  28,
  28,
  28,
  28,
  28,
  28,
  28,
  28,
  28,
  28,
  29,
  29,
  29,
  29,
  29,
  29,
  29,
  29,
  29,
  29,
  29,
  29,
  29,
  29,
  29,
  29,
  29,
  29,
  29,
  29,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
];

List<String> pageAssetPaths = [
  'assets/PDF/output_folder/page_1.png',
  'assets/PDF/output_folder/page_2.png',
  'assets/PDF/output_folder/page_3.png',
  'assets/PDF/output_folder/page_4.png',
  'assets/PDF/output_folder/page_5.png',
  'assets/PDF/output_folder/page_6.png',
  'assets/PDF/output_folder/page_7.png',
  'assets/PDF/output_folder/page_8.png',
  'assets/PDF/output_folder/page_9.png',
  'assets/PDF/output_folder/page_10.png',
  'assets/PDF/output_folder/page_11.png',
  'assets/PDF/output_folder/page_12.png',
  'assets/PDF/output_folder/page_13.png',
  'assets/PDF/output_folder/page_14.png',
  'assets/PDF/output_folder/page_15.png',
  'assets/PDF/output_folder/page_16.png',
  'assets/PDF/output_folder/page_17.png',
  'assets/PDF/output_folder/page_18.png',
  'assets/PDF/output_folder/page_19.png',
  'assets/PDF/output_folder/page_20.png',
  'assets/PDF/output_folder/page_21.png',
  'assets/PDF/output_folder/page_22.png',
  'assets/PDF/output_folder/page_23.png',
  'assets/PDF/output_folder/page_24.png',
  'assets/PDF/output_folder/page_25.png',
  'assets/PDF/output_folder/page_26.png',
  'assets/PDF/output_folder/page_27.png',
  'assets/PDF/output_folder/page_28.png',
  'assets/PDF/output_folder/page_29.png',
  'assets/PDF/output_folder/page_30.png',
  'assets/PDF/output_folder/page_31.png',
  'assets/PDF/output_folder/page_32.png',
  'assets/PDF/output_folder/page_33.png',
  'assets/PDF/output_folder/page_34.png',
  'assets/PDF/output_folder/page_35.png',
  'assets/PDF/output_folder/page_36.png',
  'assets/PDF/output_folder/page_37.png',
  'assets/PDF/output_folder/page_38.png',
  'assets/PDF/output_folder/page_39.png',
  'assets/PDF/output_folder/page_40.png',
  'assets/PDF/output_folder/page_41.png',
  'assets/PDF/output_folder/page_42.png',
  'assets/PDF/output_folder/page_43.png',
  'assets/PDF/output_folder/page_44.png',
  'assets/PDF/output_folder/page_45.png',
  'assets/PDF/output_folder/page_46.png',
  'assets/PDF/output_folder/page_47.png',
  'assets/PDF/output_folder/page_48.png',
  'assets/PDF/output_folder/page_49.png',
  'assets/PDF/output_folder/page_50.png',
  'assets/PDF/output_folder/page_51.png',
  'assets/PDF/output_folder/page_52.png',
  'assets/PDF/output_folder/page_53.png',
  'assets/PDF/output_folder/page_54.png',
  'assets/PDF/output_folder/page_55.png',
  'assets/PDF/output_folder/page_56.png',
  'assets/PDF/output_folder/page_57.png',
  'assets/PDF/output_folder/page_58.png',
  'assets/PDF/output_folder/page_59.png',
  'assets/PDF/output_folder/page_60.png',
  'assets/PDF/output_folder/page_61.png',
  'assets/PDF/output_folder/page_62.png',
  'assets/PDF/output_folder/page_63.png',
  'assets/PDF/output_folder/page_64.png',
  'assets/PDF/output_folder/page_65.png',
  'assets/PDF/output_folder/page_66.png',
  'assets/PDF/output_folder/page_67.png',
  'assets/PDF/output_folder/page_68.png',
  'assets/PDF/output_folder/page_69.png',
  'assets/PDF/output_folder/page_70.png',
  'assets/PDF/output_folder/page_71.png',
  'assets/PDF/output_folder/page_72.png',
  'assets/PDF/output_folder/page_73.png',
  'assets/PDF/output_folder/page_74.png',
  'assets/PDF/output_folder/page_75.png',
  'assets/PDF/output_folder/page_76.png',
  'assets/PDF/output_folder/page_77.png',
  'assets/PDF/output_folder/page_78.png',
  'assets/PDF/output_folder/page_79.png',
  'assets/PDF/output_folder/page_80.png',
  'assets/PDF/output_folder/page_81.png',
  'assets/PDF/output_folder/page_82.png',
  'assets/PDF/output_folder/page_83.png',
  'assets/PDF/output_folder/page_84.png',
  'assets/PDF/output_folder/page_85.png',
  'assets/PDF/output_folder/page_86.png',
  'assets/PDF/output_folder/page_87.png',
  'assets/PDF/output_folder/page_88.png',
  'assets/PDF/output_folder/page_89.png',
  'assets/PDF/output_folder/page_90.png',
  'assets/PDF/output_folder/page_91.png',
  'assets/PDF/output_folder/page_92.png',
  'assets/PDF/output_folder/page_93.png',
  'assets/PDF/output_folder/page_94.png',
  'assets/PDF/output_folder/page_95.png',
  'assets/PDF/output_folder/page_96.png',
  'assets/PDF/output_folder/page_97.png',
  'assets/PDF/output_folder/page_98.png',
  'assets/PDF/output_folder/page_99.png',
  'assets/PDF/output_folder/page_100.png',
  'assets/PDF/output_folder/page_101.png',
  'assets/PDF/output_folder/page_102.png',
  'assets/PDF/output_folder/page_103.png',
  'assets/PDF/output_folder/page_104.png',
  'assets/PDF/output_folder/page_105.png',
  'assets/PDF/output_folder/page_106.png',
  'assets/PDF/output_folder/page_107.png',
  'assets/PDF/output_folder/page_108.png',
  'assets/PDF/output_folder/page_109.png',
  'assets/PDF/output_folder/page_110.png',
  'assets/PDF/output_folder/page_111.png',
  'assets/PDF/output_folder/page_112.png',
  'assets/PDF/output_folder/page_113.png',
  'assets/PDF/output_folder/page_114.png',
  'assets/PDF/output_folder/page_115.png',
  'assets/PDF/output_folder/page_116.png',
  'assets/PDF/output_folder/page_117.png',
  'assets/PDF/output_folder/page_118.png',
  'assets/PDF/output_folder/page_119.png',
  'assets/PDF/output_folder/page_120.png',
  'assets/PDF/output_folder/page_121.png',
  'assets/PDF/output_folder/page_122.png',
  'assets/PDF/output_folder/page_123.png',
  'assets/PDF/output_folder/page_124.png',
  'assets/PDF/output_folder/page_125.png',
  'assets/PDF/output_folder/page_126.png',
  'assets/PDF/output_folder/page_127.png',
  'assets/PDF/output_folder/page_128.png',
  'assets/PDF/output_folder/page_129.png',
  'assets/PDF/output_folder/page_130.png',
  'assets/PDF/output_folder/page_131.png',
  'assets/PDF/output_folder/page_132.png',
  'assets/PDF/output_folder/page_133.png',
  'assets/PDF/output_folder/page_134.png',
  'assets/PDF/output_folder/page_135.png',
  'assets/PDF/output_folder/page_136.png',
  'assets/PDF/output_folder/page_137.png',
  'assets/PDF/output_folder/page_138.png',
  'assets/PDF/output_folder/page_139.png',
  'assets/PDF/output_folder/page_140.png',
  'assets/PDF/output_folder/page_141.png',
  'assets/PDF/output_folder/page_142.png',
  'assets/PDF/output_folder/page_143.png',
  'assets/PDF/output_folder/page_144.png',
  'assets/PDF/output_folder/page_145.png',
  'assets/PDF/output_folder/page_146.png',
  'assets/PDF/output_folder/page_147.png',
  'assets/PDF/output_folder/page_148.png',
  'assets/PDF/output_folder/page_149.png',
  'assets/PDF/output_folder/page_150.png',
  'assets/PDF/output_folder/page_151.png',
  'assets/PDF/output_folder/page_152.png',
  'assets/PDF/output_folder/page_153.png',
  'assets/PDF/output_folder/page_154.png',
  'assets/PDF/output_folder/page_155.png',
  'assets/PDF/output_folder/page_156.png',
  'assets/PDF/output_folder/page_157.png',
  'assets/PDF/output_folder/page_158.png',
  'assets/PDF/output_folder/page_159.png',
  'assets/PDF/output_folder/page_160.png',
  'assets/PDF/output_folder/page_161.png',
  'assets/PDF/output_folder/page_162.png',
  'assets/PDF/output_folder/page_163.png',
  'assets/PDF/output_folder/page_164.png',
  'assets/PDF/output_folder/page_165.png',
  'assets/PDF/output_folder/page_166.png',
  'assets/PDF/output_folder/page_167.png',
  'assets/PDF/output_folder/page_168.png',
  'assets/PDF/output_folder/page_169.png',
  'assets/PDF/output_folder/page_170.png',
  'assets/PDF/output_folder/page_171.png',
  'assets/PDF/output_folder/page_172.png',
  'assets/PDF/output_folder/page_173.png',
  'assets/PDF/output_folder/page_174.png',
  'assets/PDF/output_folder/page_175.png',
  'assets/PDF/output_folder/page_176.png',
  'assets/PDF/output_folder/page_177.png',
  'assets/PDF/output_folder/page_178.png',
  'assets/PDF/output_folder/page_179.png',
  'assets/PDF/output_folder/page_180.png',
  'assets/PDF/output_folder/page_181.png',
  'assets/PDF/output_folder/page_182.png',
  'assets/PDF/output_folder/page_183.png',
  'assets/PDF/output_folder/page_184.png',
  'assets/PDF/output_folder/page_185.png',
  'assets/PDF/output_folder/page_186.png',
  'assets/PDF/output_folder/page_187.png',
  'assets/PDF/output_folder/page_188.png',
  'assets/PDF/output_folder/page_188.png',
  'assets/PDF/output_folder/page_189.png',
  'assets/PDF/output_folder/page_190.png',
  'assets/PDF/output_folder/page_191.png',
  'assets/PDF/output_folder/page_192.png',
  'assets/PDF/output_folder/page_193.png',
  'assets/PDF/output_folder/page_194.png',
  'assets/PDF/output_folder/page_195.png',
  'assets/PDF/output_folder/page_196.png',
  'assets/PDF/output_folder/page_197.png',
  'assets/PDF/output_folder/page_198.png',
  'assets/PDF/output_folder/page_199.png',
  'assets/PDF/output_folder/page_200.png',
  'assets/PDF/output_folder/page_201.png',
  'assets/PDF/output_folder/page_202.png',
  'assets/PDF/output_folder/page_203.png',
  'assets/PDF/output_folder/page_204.png',
  'assets/PDF/output_folder/page_205.png',
  'assets/PDF/output_folder/page_206.png',
  'assets/PDF/output_folder/page_207.png',
  'assets/PDF/output_folder/page_208.png',
  'assets/PDF/output_folder/page_209.png',
  'assets/PDF/output_folder/page_210.png',
  'assets/PDF/output_folder/page_211.png',
  'assets/PDF/output_folder/page_212.png',
  'assets/PDF/output_folder/page_213.png',
  'assets/PDF/output_folder/page_214.png',
  'assets/PDF/output_folder/page_215.png',
  'assets/PDF/output_folder/page_216.png',
  'assets/PDF/output_folder/page_217.png',
  'assets/PDF/output_folder/page_218.png',
  'assets/PDF/output_folder/page_219.png',
  'assets/PDF/output_folder/page_220.png',
  'assets/PDF/output_folder/page_221.png',
  'assets/PDF/output_folder/page_222.png',
  'assets/PDF/output_folder/page_223.png',
  'assets/PDF/output_folder/page_224.png',
  'assets/PDF/output_folder/page_225.png',
  'assets/PDF/output_folder/page_226.png',
  'assets/PDF/output_folder/page_227.png',
  'assets/PDF/output_folder/page_228.png',
  'assets/PDF/output_folder/page_229.png',
  'assets/PDF/output_folder/page_230.png',
  'assets/PDF/output_folder/page_231.png',
  'assets/PDF/output_folder/page_232.png',
  'assets/PDF/output_folder/page_233.png',
  'assets/PDF/output_folder/page_234.png',
  'assets/PDF/output_folder/page_235.png',
  'assets/PDF/output_folder/page_236.png',
  'assets/PDF/output_folder/page_237.png',
  'assets/PDF/output_folder/page_238.png',
  'assets/PDF/output_folder/page_239.png',
  'assets/PDF/output_folder/page_240.png',
  'assets/PDF/output_folder/page_241.png',
  'assets/PDF/output_folder/page_242.png',
  'assets/PDF/output_folder/page_243.png',
  'assets/PDF/output_folder/page_244.png',
  'assets/PDF/output_folder/page_245.png',
  'assets/PDF/output_folder/page_246.png',
  'assets/PDF/output_folder/page_247.png',
  'assets/PDF/output_folder/page_248.png',
  'assets/PDF/output_folder/page_249.png',
  'assets/PDF/output_folder/page_250.png',
  'assets/PDF/output_folder/page_251.png',
  'assets/PDF/output_folder/page_252.png',
  'assets/PDF/output_folder/page_253.png',
  'assets/PDF/output_folder/page_254.png',
  'assets/PDF/output_folder/page_255.png',
  'assets/PDF/output_folder/page_256.png',
  'assets/PDF/output_folder/page_257.png',
  'assets/PDF/output_folder/page_258.png',
  'assets/PDF/output_folder/page_259.png',
  'assets/PDF/output_folder/page_260.png',
  'assets/PDF/output_folder/page_261.png',
  'assets/PDF/output_folder/page_262.png',
  'assets/PDF/output_folder/page_263.png',
  'assets/PDF/output_folder/page_264.png',
  'assets/PDF/output_folder/page_265.png',
  'assets/PDF/output_folder/page_266.png',
  'assets/PDF/output_folder/page_267.png',
  'assets/PDF/output_folder/page_268.png',
  'assets/PDF/output_folder/page_269.png',
  'assets/PDF/output_folder/page_270.png',
  'assets/PDF/output_folder/page_271.png',
  'assets/PDF/output_folder/page_272.png',
  'assets/PDF/output_folder/page_273.png',
  'assets/PDF/output_folder/page_274.png',
  'assets/PDF/output_folder/page_275.png',
  'assets/PDF/output_folder/page_276.png',
  'assets/PDF/output_folder/page_277.png',
  'assets/PDF/output_folder/page_278.png',
  'assets/PDF/output_folder/page_279.png',
  'assets/PDF/output_folder/page_280.png',
  'assets/PDF/output_folder/page_281.png',
  'assets/PDF/output_folder/page_282.png',
  'assets/PDF/output_folder/page_283.png',
  'assets/PDF/output_folder/page_284.png'
];

List<String> azkar_sobh = [
  "أَعُوذُ بِاللهِ مِنْ الشَّيْطَانِ الرَّجِيمِ\nاللّهُ لاَ إِلَـهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ لاَ تَأْخُذُهُ سِنَةٌ وَلاَ نَوْمٌ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلاَّ بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلاَ يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلاَّ بِمَا شَاء وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالأَرْضَ وَلاَ يَؤُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ.",
  "بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم\nقُلْ هُوَ ٱللَّهُ أَحَدٌ، ٱللَّهُ ٱلصَّمَدُ، لَمْ يَلِدْ وَلَمْ يُولَدْ، وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ.",
  "بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم\nقُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ، مِن شَرِّ مَا خَلَقَ، وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ، وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ، وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ.",
  "بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم\nقُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ، مَلِكِ ٱلنَّاسِ، إِلَٰهِ ٱلنَّاسِ، مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ، ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ، مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ.",
  "أَصْـبَحْنا وَأَصْـبَحَ المُـلْكُ لله وَالحَمدُ لله ، لا إلهَ إلاّ اللّهُ وَحدَهُ لا شَريكَ لهُ، لهُ المُـلكُ ولهُ الحَمْـد، وهُوَ على كلّ شَيءٍ قدير ، رَبِّ أسْـأَلُـكَ خَـيرَ ما في هـذا اليوم وَخَـيرَ ما بَعْـدَه ، وَأَعـوذُ بِكَ مِنْ شَـرِّ ما في هـذا اليوم وَشَرِّ ما بَعْـدَه، رَبِّ أَعـوذُبِكَ مِنَ الْكَسَـلِ وَسـوءِ الْكِـبَر ، رَبِّ أَعـوذُ بِكَ مِنْ عَـذابٍ في النّـارِ وَعَـذابٍ في القَـبْر.",
  "اللّهـمَّ أَنْتَ رَبِّـي لا إلهَ إلاّ أَنْتَ، خَلَقْتَنـي وَأَنا عَبْـدُك، وَأَنا عَلـى عَهْـدِكَ وَوَعْـدِكَ ما اسْتَـطَعْـت، أَعـوذُبِكَ مِنْ شَـرِّ ما صَنَـعْت، أَبـوءُ لَـكَ بِنِعْـمَتِـكَ عَلَـيَّ وَأَبـوءُ بِذَنْـبي فَاغْفـِرْ لي فَإِنَّـهُ لا يَغْـفِرُ الذُّنـوبَ إِلاّ أَنْتَ.",
  "رَضيـتُ بِاللهِ رَبَّـاً وَبِالإسْلامِ ديـناً وَبِمُحَـمَّدٍ صلى الله عليه وسلم نَبِيّـاً.",
  "اللّهُـمَّ إِنِّـي أَصْبَـحْتُ أُشْـهِدُك، وَأُشْـهِدُ حَمَلَـةَ عَـرْشِـك، وَمَلائِكَتَكَ، وَجَمـيعَ خَلْـقِك، أَنَّـكَ أَنْـتَ اللهُ لا إلهَ إلاّ أَنْـتَ وَحْـدَكَ لا شَريكَ لَـكَ، وَأَنَّ ُ مُحَمّـداً عَبْـدُكَ وَرَسـولُـك.",
  "اللّهُـمَّ ما أَصْبَـَحَ بي مِـنْ نِعْـمَةٍ أَو بِأَحَـدٍ مِـنْ خَلْـقِك ، فَمِـنْكَ وَحْـدَكَ لا شريكَ لَـك ، فَلَـكَ الْحَمْـدُ وَلَـكَ الشُّكْـر.",
  "حَسْبِـيَ اللّهُ لا إلهَ إلاّ هُوَ عَلَـيهِ تَوَكَّـلتُ وَهُوَ رَبُّ العَرْشِ العَظـيم.",
  "بِسـمِ اللهِ الذي لا يَضُـرُّ مَعَ اسمِـهِ شَيءٌ في الأرْضِ وَلا في السّمـاءِ وَهـوَ السّمـيعُ العَلـيم.",
  "اللّهـمَّ بِكَ أَصْـبَحْنا وَبِكَ أَمْسَـينا، وَبِكَ نَحْـيا وَبِكَ نَمُـوتُ وَإِلَـيْكَ النُّـشُور.",
  "أَصْبَـحْـنا عَلَى فِطْرَةِ الإسْلاَمِ، وَعَلَى كَلِمَةِ الإِخْلاَصِ، وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ، وَعَلَى مِلَّةِ أَبِينَا إبْرَاهِيمَ حَنِيفاً مُسْلِماً وَمَا كَانَ مِنَ المُشْرِكِينَ.",
  "سُبْحـانَ اللهِ وَبِحَمْـدِهِ عَدَدَ خَلْـقِه ، وَرِضـا نَفْسِـه ، وَزِنَـةَ عَـرْشِـه ، وَمِـدادَ كَلِمـاتِـه. ",
  "اللّهُـمَّ عافِـني في بَدَنـي ، اللّهُـمَّ عافِـني في سَمْـعي ، اللّهُـمَّ عافِـني في بَصَـري ، لا إلهَ إلاّ أَنْـتَ.",
  "اللّهُـمَّ إِنّـي أَعـوذُ بِكَ مِنَ الْكُـفر ، وَالفَـقْر ، وَأَعـوذُ بِكَ مِنْ عَذابِ القَـبْر ، لا إلهَ إلاّ أَنْـتَ.",
  "اللّهُـمَّ إِنِّـي أسْـأَلُـكَ العَـفْوَ وَالعـافِـيةَ في الدُّنْـيا وَالآخِـرَة ، اللّهُـمَّ إِنِّـي أسْـأَلُـكَ العَـفْوَ وَالعـافِـيةَ في ديني وَدُنْـيايَ وَأهْـلي وَمالـي ، اللّهُـمَّ اسْتُـرْ عـوْراتي وَآمِـنْ رَوْعاتـي ، اللّهُـمَّ احْفَظْـني مِن بَـينِ يَدَيَّ وَمِن خَلْفـي وَعَن يَمـيني وَعَن شِمـالي ، وَمِن فَوْقـي ، وَأَعـوذُ بِعَظَمَـتِكَ أَن أُغْـتالَ مِن تَحْتـي.",
  "يَا حَيُّ يَا قيُّومُ بِرَحْمَتِكَ أسْتَغِيثُ أصْلِحْ لِي شَأنِي كُلَّهُ وَلاَ تَكِلْنِي إلَى نَفْسِي طَـرْفَةَ عَيْنٍ. ",
  "أَصْبَـحْـنا وَأَصْبَـحْ المُـلكُ للهِ رَبِّ العـالَمـين ، اللّهُـمَّ إِنِّـي أسْـأَلُـكَ خَـيْرَ هـذا الـيَوْم ، فَـتْحَهُ ، وَنَصْـرَهُ ، وَنـورَهُ وَبَـرَكَتَـهُ ، وَهُـداهُ ، وَأَعـوذُ بِـكَ مِـنْ شَـرِّ ما فـيهِ وَشَـرِّ ما بَعْـدَه.",
  "اللّهُـمَّ عالِـمَ الغَـيْبِ وَالشّـهادَةِ فاطِـرَ السّماواتِ وَالأرْضِ رَبَّ كـلِّ شَـيءٍ وَمَليـكَه ، أَشْهَـدُ أَنْ لا إِلـهَ إِلاّ أَنْت ، أَعـوذُ بِكَ مِن شَـرِّ نَفْسـي وَمِن شَـرِّ الشَّيْـطانِ وَشِرْكِهِ ، وَأَنْ أَقْتَـرِفَ عَلـى نَفْسـي سوءاً أَوْ أَجُـرَّهُ إِلـى مُسْـلِم.",
  "أَعـوذُ بِكَلِمـاتِ اللّهِ التّـامّـاتِ مِنْ شَـرِّ ما خَلَـق.",
  "اللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ على نَبِيِّنَا مُحمَّد",
  "اللَّهُمَّ إِنَّا نَعُوذُ بِكَ مِنْ أَنْ نُشْرِكَ بِكَ شَيْئًا نَعْلَمُهُ ، وَنَسْتَغْفِرُكَ لِمَا لَا نَعْلَمُهُ.",
  "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنْ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنْ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ، وَقَهْرِ الرِّجَالِ.",
  "أسْتَغْفِرُ اللهَ العَظِيمَ الَّذِي لاَ إلَهَ إلاَّ هُوَ، الحَيُّ القَيُّومُ، وَأتُوبُ إلَيهِ.",
  "يَا رَبِّ , لَكَ الْحَمْدُ كَمَا يَنْبَغِي لِجَلَالِ وَجْهِكَ , وَلِعَظِيمِ سُلْطَانِكَ.",
  "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا.",
  "اللَّهُمَّ أَنْتَ رَبِّي لا إِلَهَ إِلا أَنْتَ ، عَلَيْكَ تَوَكَّلْتُ ، وَأَنْتَ رَبُّ الْعَرْشِ الْعَظِيمِ , مَا شَاءَ اللَّهُ كَانَ ، وَمَا لَمْ يَشَأْ لَمْ يَكُنْ ، وَلا حَوْلَ وَلا قُوَّةَ إِلا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ , أَعْلَمُ أَنَّ اللَّهَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ ، وَأَنَّ اللَّهَ قَدْ أَحَاطَ بِكُلِّ شَيْءٍ عِلْمًا , اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي ، وَمِنْ شَرِّ كُلِّ دَابَّةٍ أَنْتَ آخِذٌ بِنَاصِيَتِهَا ، إِنَّ رَبِّي عَلَى صِرَاطٍ مُسْتَقِيمٍ.",
  "لَا إلَه إلّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءِ قَدِيرِ. ",
  "سُبْحـانَ اللهِ وَبِحَمْـدِهِ.",
  "أسْتَغْفِرُ اللهَ وَأتُوبُ إلَيْهِ",
  "qsdqsdqsds"
];
const times_sobh = [
  1,
  3,
  3,
  3,
  1,
  1,
  3,
  4,
  1,
  7,
  3,
  1,
  1,
  3,
  3,
  3,
  1,
  3,
  1,
  1,
  3,
  10,
  3,
  3,
  3,
  3,
  1,
  1,
  100,
  100,
  100,
  0
];

const azkar_masaa = [];
const azkar_noom = [];
const azkar_salaa = [];
const azkar_wakeUp = [];
const azkar_mosque = [];
const azkar_mathoora = [];
const azkar_quran = [];
const azkar_travel = [];
const azkar_roqya = [];
